markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: rechardchen.github.io
title: Rechardchen's Blog
description: A man with great interest of the world
author: rechardchen
email: rechard_chen@qq.com
github: rechardchen

config:
  js_dir:
  img_dir:
  css_dir:
